services:
  Siketyan\Loxcan\Versioning\Composer\ComposerVersionParser: ~

  Siketyan\Loxcan\Versioning\Composer\ComposerVersionComparator: ~

  Siketyan\Loxcan\Versioning\Simple\SimpleVersionComparator: ~

  Siketyan\Loxcan\Versioning\VersionComparatorResolver:
    arguments:
      $comparators:
        - '@Siketyan\Loxcan\Versioning\Simple\SimpleVersionComparator'
        - '@Siketyan\Loxcan\Versioning\Composer\ComposerVersionComparator'
