name: Docker

on:
  push:
    branches:
      - main
      - build/push-to-ghcr
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get shorter hash of the commit
        id: shorter_hash
        run: echo "::set-output name=hash::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/siketyan/loxcan:${{ steps.shorter_hash.outputs.hash }}
            ghcr.io/siketyan/loxcan:${{ github.event.release.tag_name || 'latest' }}
