name: PHP

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !(github.event.pull_request && github.actor == github.repository_owner) }}
    strategy:
      matrix:
        php:
          - '8.1'
          # - '8.2'
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Run linter
        run: composer run-script lint

      - name: Run test suite
        run: composer run-script codecov

      - uses: codecov/codecov-action@v1
        if: ${{ matrix.php }} == '8.1'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          verbose: true
